name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */6 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -e .
      - run: source-hunter run --json | tee output.json
      - uses: actions/upload-artifact@v4
        with:
          name: source-hunter-output
          path: |
            output.json
            registry/*.json
